# Generated by Django 4.1.4 on 2024-05-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='question_text',
            new_name='message_text',
        ),
    ]
