# Generated by Django 4.1.4 on 2024-05-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_question_text_message_message_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
